BlogProject-seed/BlogProject/Areas/Admin/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace BlogProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class AdminCategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryRepository());
        public IActionResult Index(int page=1)
        {
            var values = categoryManager.TGetList().ToPagedList(page, 7);
            return View(values);
        }

        [HttpGet]
        public IActionResult CategoryAdd()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CategoryAdd(Category p)
        {
            if (ModelState.IsValid)
            {
                categoryManager.TAdd(p);
                return RedirectToAction("Index");
            }
            return View(p);
        }

        public IActionResult CategoryDelete(int id)
        {
            var value = categoryManager.TGetByID(id);
            categoryManager.TDelete(value);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult CategoryUpdate(int id)
        {
            var value = categoryManager.TGetByID(id);
            return View(value);
        }
        [HttpPost]
        public IActionResult CategoryUpdate(Category p)
        {
            if (ModelState.IsValid)
            {
                categoryManager.TUpdate(p);
                return RedirectToAction("Index");
            }
            return View(p);
        }
    }
}

BlogProject-seed/BlogProject/Areas/Admin/Views/AdminCategory/CategoryAdd.cshtml
@model Category

@{
    ViewData["Title"] = "CategoryAdd";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h1>Kategori Ekleme</h1>

<form method="post" asp-area="Admin" asp-controller="AdminCategory" asp-action="CategoryAdd">
    <div class="form-group">
        <label>Kategori Adı</label>
        @Html.TextBoxFor(x=>x.CategoryName, new {@class="form-control"})
        <span asp-validation-for="@Model.CategoryName" style="color:red"></span>
    </div>

    <div class="text-danger" asp-validation-summary="ModelOnly">
    </div>
    <button type="submit" class="btn btn-success btn-lg mb-3"> Ekle </button>
    <br />
    <a asp-area="Admin" asp-controller="AdminCategory" asp-action="Index" class="btn btn-primary btn-lg"> Geri Dön </a>

</form>

BlogProject-seed/BlogProject/Areas/Admin/Views/AdminCategory/CategoryUpdate.cshtml
@model Category

@{
    ViewData["Title"] = "CategoryUpdate";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}

<h1>Kategori Güncelleme</h1>

<form method="post" asp-area="Admin" asp-controller="AdminCategory" asp-action="CategoryUpdate">
    @Html.HiddenFor(x=>x.CategoryID)
    <div class="form-group">
        <label>Kategori Adı</label>
        @Html.TextBoxFor(x=>x.CategoryName, new {@class = "form-control"})
        <span asp-validation-for="@Model.CategoryName" style="color:red"></span>
    </div>
    <button type="submit" class="btn btn-lg btn-outline-primary">Güncelle</button>
    <a asp-area="Admin" asp-controller="AdminCategory" asp-action="Index" class="btn btn-primary btn-lg"> Geri Dön </a>
</form>

BlogProject-seed/BlogProject/Areas/Admin/Views/AdminCategory/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@using X.PagedList.Web.Common;

@model IPagedList<Category>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/AdminLayout.cshtml";
}
<link href="~/inspinia-gh-pages/css/pagedd.css" rel="stylesheet" />
<h1>Kategori Listesi</h1>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>
@{
    var id = 0;
}
<br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Adı</th>
        <th>SİL</th>
        <th>Düzenle</th>
    </tr>
    @foreach (var item in Model)
    {
        id = item.CategoryID;
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td> <a href="/Admin/AdminCategory/CategoryDelete/@item.CategoryID" id="DeleteBtn" onclick="return confirm('@item.CategoryName.ToUpper() kategorisi silinecek. Silmek istediğinize Emin misiniz');" class="btn btn-danger btn-lg">SİL</a>  </td>
            <td> <a href="/Admin/AdminCategory/CategoryUpdate/@item.CategoryID" class="btn btn-primary">Düzenle</a>  </td>


        </tr>

    }

</table>
@{
    var durum = "";
    if (Model.Count() < 7)
    {
        durum = "visibility:hidden";
    }
    else
    {
        durum = "visibility:visible";
    }
}
<div class="pagination" style="justify-content:center;@durum">

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }),
    new PagedListRenderOptions
    {
    LinkToPreviousPageFormat = "< Önceki",
    LinkToNextPageFormat = "Sonraki >",
    LiElementClasses = new string[] { "page-item"},
    PageClasses = new string[] {"page-link"}
    })
</div>


@* <a href="AdminCategory/CategoryAdd" class="btn btn-primary">Yeni Kategori</a> *@
@* <a href="/Admin/AdminCategory/CategoryAdd" class="btn btn-primary">Yeni Kategori</a> *@
<a asp-area="Admin" asp-controller="AdminCategory" asp-action="CategoryAdd" class="btn btn-primary">Yeni Kategori</a>
<br />
<br />